### ISSUE TITLE
如何获取 cookie & uid

### ISSUE THREAD

**Issue by danielliulihua** [chen310/NeteasePotPlayer#1]
如何获得自己的 cookie 和uid?

**Comment by chen310** [comment]
cookie 获取方式：首先在网页登录[网易云音乐](https://music.163.com/)，然后按 <kbd>F12</kbd> 打开开发人员工具，再按 <kbd>F5</kbd> 刷新页面，最后按照以下步骤来获取 cookie

![Cookie](https://cdn.jsdelivr.net/gh/chen310/NeteaseCloudMusicTasks/public/img/cookie.png)

**Comment by chen310** [comment]
uid获取方式: 网易云音乐 APP 中，在个人主页右上角分享，获取链接，链接中 id= 后面的数字即为 uid

网页端个人主页链接中 id= 后面的数字也为 uid

**Comment by danielliulihua** [comment]
Thanks

> uid获取方式: 网易云音乐 APP 中，在个人主页右上角分享，获取链接，链接中 id= 后面的数字即为 uid
> 
> 网页端个人主页链接中 id= 后面的数字也为 uid

Thanks

**Comment by danielliulihua** [comment]
Thanks
